if(CMAKE_BUILD_TYPE STREQUAL Release)
    message("~~~~~~~~~~~~~~Release~~~~~~~~~~~~~~~")
    if(WIN32 AND NOT MINGW)
        message("~~~~~~~~~WIN32 Configuration~~~~~~~~")
    elseif(WIN32 AND MINGW)
        message("~~~~~~~~~MINGW Configuration~~~~~~~~")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
    elseif(UNIX AND NOT ANDROID)
        message("~~~~~~~~~UNIX Configuration~~~~~~~~~")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
    endif()
else()
    message("~~~~~~~~~~~~~~~Debug~~~~~~~~~~~~~~~~")
    if(WIN32 AND NOT MINGW)
        message("~~~~~~~~~WIN32 Configuration~~~~~~~~")
    elseif(WIN32 AND MINGW)
        message("~~~~~~~~~MINGW Configuration~~~~~~~~")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g2")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -ggdb")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wfatal-errors")
    elseif(UNIX AND NOT ANDROID)
        message("~~~~~~~~~UNIX Configuration~~~~~~~~~")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g2")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -ggdb")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wfatal-errors")
        if(Sanitize STREQUAL Address)
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=address -fno-omit-frame-pointer")
        elseif(Sanitize STREQUAL Thread)
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=thread -pie -g")
        endif()
    endif()
endif()
# Platform
if(WIN32)
    #WIN32 Library
    set(PLATFORM
        ws2_32
        mswsock
    )
elseif(UNIX)
    #UNIX Library
    set(PLATFORM
    )
endif()

# ThirdParty
find_library(SSL_LIBRARY ssl)
find_path(OPENSSL openssl/conf.h)
find_library(CRYPTO_LIBRARY crypto)
if(NOT ${SSL} STREQUAL "SSL-NOTFOUND" AND NOT ${CRYPTO} STREQUAL "CRYPTO-NOTFOUND")
    add_definitions(-DOPENSSL)
    include_directories(${OPENSSL})
    message("Found Header: ${OPENSSL}")
    message("Found Library: ${SSL_LIBRARY}")
    message("Found Library: ${CRYPTO_LIBRARY}")
    set(THIRDPARTY ${THIRDPARTY} ${SSL_LIBRARY} ${CRYPTO_LIBRARY})
endif()

link_libraries(${PLATFORM} ${THIRDPARTY})